### ISSUE TITLE
arma-reforger exited with code 0

### ISSUE THREAD

**Issue by troilus** [acemod/docker-reforger#38]
**Describe the bug**
arma-reforger exited with code 0

**To Reproduce**
docker-compose up

**Screenshots / Output**

arma-reforger    | Success! App '1874900' fully installed.
arma-reforger    | Admin password: unconventional-assembled
arma-reforger    | ./ArmaReforgerServer -config /reforger/Configs/docker_generated.json -backendlog -nothrow -maxFPS 120 -profile /home/profile -addonDownloadDir /reforger/workshop -addonsDir /reforger/workshop
arma-reforger    | ENGINE       : GameProject load
arma-reforger    |  INIT         : GameProject load project data @"./addons/data/ArmaReforger.gproj"
arma-reforger    |   RESOURCES (E): Wrong GUID/name for resource @"{C014582791ECBF24}Language/localization.st" in property "StringTableSource"
arma-reforger    | ENGINE    (W): Enfusion setting file load failed ($profile:.save/settings/ReforgerEngineSettings.conf)
arma-reforger    | SCRIPT       : Compiling Game scripts
arma-reforger    |  SCRIPT    (W): @"scripts/Game/Components/SCR_XPHandlerComponent.c,34": 'OnPlayerSpawned' is obsolete: Use OnPlayerSpawnFinalize_S instead
arma-reforger    |  SCRIPT    (W): @"scripts/Game/GameMode/Respawn/SCR_WaveRespawnTimerComponent.c,103": 'OnPlayerSpawned' is obsolete: Use OnPlayerSpawnFinalize_S instead
arma-reforger    |  SCRIPT    (W): @"scripts/Game/UI/Inventory/SCR_InventoryMenuUI.c,522": No need to use 'Cast' for up-casting
arma-reforger    |  SCRIPT    (W): @"scripts/Game/UI/ScreenEffects/SCR_DeathScreenEffect.c,55": No need to use 'Cast' for up-casting
arma-reforger    |  SCRIPT    (W): @"scripts/Game/Workshop/SCR_WorkshopItem.c,715": 'GetSizeBytes' is obsolete: Use Revision.GetSizeBytes() instead.
arma-reforger    | BACKEND      : Loading dedicated server config.
arma-reforger    |  BACKEND      : JSON Schema Validation:
arma-reforger    |   BACKEND      : pattern error:
arma-reforger    |    BACKEND   (E): Value of "#/game/scenarioId" does not match the required pattern. Value: ""{C41618FD18E9D714}Missions/23_Campaign_Arland.conf""
arma-reforger    |    BACKEND   (E): RegEx Pattern: "^\{[0-9A-F]{16}\}[a-zA-Z0-9_./ -]+$"
arma-reforger    |    BACKEND   (E): Pattern Description: "Param must start with scenarioId enclosed in brackets: {ECC61978EDCC2B5A}"
arma-reforger    |    BACKEND   (E): Reference in schema: "#/properties/game/properties/scenarioId"
arma-reforger    |   BACKEND   (E): JSON is invalid!
arma-reforger    |  BACKEND   (E): There are errors in server config!
arma-reforger    | BACKEND   (E): Unable to continue with a broken DS config! Shutdown!
arma-reforger    | ENGINE    (E): Error while initializing game.
arma-reforger    | ENGINE    (E): Unable to initialize the game
arma-reforger    | ENGINE    (E): BackendDebug:: HttpClient Cleanup
arma-reforger    | ENGINE       : Creating engine.
arma-reforger    | ENGINE       : FileSystem: Adding relative directory '/home/profile/logs/logs_2024-04-11_03-35-18' to filesystem under name logs
arma-reforger    | ENGINE       : FileSystem: Adding relative directory '/home/profile/profile' to filesystem under name profile
arma-reforger    | ENGINE       : Initializing engine.
arma-reforger    | ENGINE       : CLI Params: -config /reforger/Configs/docker_generated.json -backendlog -nothrow -maxFPS 120 -profile /home/profile -addonDownloadDir /reforger/workshop -addonsDir /reforger/workshop
arma-reforger    | ENGINE       : Addon dirs:
arma-reforger    |  ENGINE       : dir: '/reforger/workshop'
arma-reforger    |  ENGINE       : dir: './addons'
arma-reforger    |  ENGINE       : dir: '/home/profile/addons'
arma-reforger    | ENGINE       : Available addons:
arma-reforger    |  ENGINE       : gproj: './addons/core/core.gproj' guid: '5614BBCCBB55ED1C' (packed)
arma-reforger    |  ENGINE       : gproj: './addons/data/ArmaReforger.gproj' guid: '58D0FB3206B6F859' (packed)
arma-reforger    | ENGINE       : FileSystem: Adding package './addons/data/' (pak count: 3) to filesystem under name ArmaReforger
arma-reforger    | ENGINE       : FileSystem: Adding package './addons/core/' (pak count: 1) to filesystem under name core
arma-reforger    | RESOURCES    : ResourceDB: loading cache (id=0 name=ArmaReforger path=./addons/data/resourceDatabase.rdb)
arma-reforger    | RESOURCES    : ResourceDB: loading cache (id=1 name=core path=./addons/core/resourceDatabase.rdb)
arma-reforger    | RESOURCES    : ResourceDB: loading cache (id=2 name=profile path=/home/profile/profile/resourceDatabase.rdb)
arma-reforger    | RESOURCES    : ResourceDB: loading cache (id=3 name=logs path=/home/profile/logs/logs_2024-04-11_03-35-18/resourceDatabase.rdb)
arma-reforger    | ENGINE       : GameProject load
arma-reforger    |  ENGINE       : Loaded addons:
arma-reforger    |   ENGINE       : gproj: './addons/core/core.gproj' guid: '5614BBCCBB55ED1C'
arma-reforger    |   ENGINE       : gproj: './addons/data/ArmaReforger.gproj' guid: '58D0FB3206B6F859'
arma-reforger    | ENGINE       : Loading custom engine user config '$profile:.save/settings/ReforgerEngineSettings.conf'
arma-reforger    | RENDER       : Basic screen setup:
arma-reforger    | RENDER       :   Back buffer width x height: 0x0
arma-reforger    | RENDER       :   Back buffer format	       : TEXFMT_UNKNOWN (0)
arma-reforger    | RENDER       :   MSAA                      : none
arma-reforger    | RENDER       : GPU_DUMMY (0xFFFF) (Enfusion dummy render) with 1 GPU detected, VRAM 128MB (fast 128MB), shared 128MB, driver version Unknown version, stereo not available
arma-reforger    | RENDER       : Detected output devices:
arma-reforger    | RENDER       :  * 1 device/s connected to Dummy:
arma-reforger    | RENDER       :    Dummy output (Dummy device for our dummy render.), 1920x1080 (offset 0x0), 60Hz
arma-reforger    | RENDER       :   Concurrent frames limit 2
arma-reforger    | ENGINE       : Job system settings: coreCount=2, shortJobContextCount=2, shortJobThreadCount=1, longJobThreadCount=1
arma-reforger    | AUDIO        : Audio device created
arma-reforger    | ENGINE       : Initializing inputs.
arma-reforger    | NETWORK      : Initializing networking.
arma-reforger    | SCRIPT       : SCRIPT       : Initializing scripts
arma-reforger    |  SCRIPT       : SCRIPT       : ScriptProjectManager init
arma-reforger    |  PROFILING    : ScriptProjectManager init took: 0.167000 ms
arma-reforger    | PROFILING    : Initializing scripts took: 155.758000 ms
arma-reforger    | ENGINE       : Enfusion engine successfully created.
arma-reforger    | GUI          : Using default language (en_us)
arma-reforger    | GUI          : Loading 'en_us' localization file.
arma-reforger    | INIT         : INIT         : Loading StringTable
arma-reforger    | PROFILING    : Loading StringTable took: 229.223000 ms
arma-reforger    | SCRIPT       : SCRIPT       : Compiling GameLib scripts
arma-reforger    |  SCRIPT       : Module: GameLib; loaded 271x files; 492x classes; used 453/2097 kB (21%) of static memory; defines: "PLATFORM_LINUX,ENF_ENABLE_VHC_OVERRIDE"; CRC32: 2d6792ab
arma-reforger    | PROFILING    : Compiling GameLib scripts took: 235.721000 ms
arma-reforger    | SCRIPT       : SCRIPT       : Compiling Game scripts
arma-reforger    |  SCRIPT       : Module: Game; loaded 3864x files; 8184x classes; used 17705/41943 kB (42%) of static memory; defines: "PLATFORM_LINUX,ENF_ENABLE_VHC_OVERRIDE,ENABLE_BASE_DESTRUCTION,DEBUG,RESPAWN_TIMER_COMPONENT_DEBUG,DEBUG_NEARBY_CONTEXT_DISPLAY,DEBUG_CONFIGURABLE_DIALOGS,DISABLE_WEAPON_SWITCHING,SCRIPTED_AIM_MODIFIER_DEBUG"; CRC32: 5ddb87c7
arma-reforger    | PROFILING    : Compiling Game scripts took: 12911.889000 ms
arma-reforger    | INIT         : Creating game instance(ArmaReforgerScripted), version 1.1.0.42 built 2024-03-20 3:04:59 UTC.
arma-reforger    | BACKEND      : Loading dedicated server config.
arma-reforger    |  BACKEND      : Server config loaded.
arma-reforger    | ENGIRESOURCES (E): ==== Resource leaks ====
arma-reforger    | RESOURCES (E): ui/fonts/robotomono_msdf_28.edds   1
arma-reforger    | NE       : Game destroyed.
arma-reforger    | RPL          : Pip::Destroy
arma-reforger exited with code 0

**Comment by hafometh88** [comment]
could you also provide your `docker-compose.yml`?

`arma-reforger | BACKEND (E): Value of "#/game/scenarioId" does not match the required pattern. Value: ""{C41618FD18E9D714}Missions/23_Campaign_Arland.conf""`

I think this is the problem, you have double brackets around the scenarioId

**Comment by troilus** [comment]
> could you also provide your `docker-compose.yml`?
> 
> `arma-reforger | BACKEND (E): Value of "#/game/scenarioId" does not match the required pattern. Value: ""{C41618FD18E9D714}Missions/23_Campaign_Arland.conf""`
> 
> I think this is the problem, you have double quotes around the scenarioId

The `docker-compose.yml` is:
```
---
version: '3.8'
services:
  arma-reforger:
    image: ghcr.dockerproxy.com/acemod/arma-reforger:latest
    platform: linux/amd64
    container_name: arma-reforger
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "19999:19999/udp"  # RCON
    volumes:
      - ./reforger/configs:/reforger/Configs
      - ./reforger/profile:/home/profile
      - ./reforger/workshop:/reforger/workshop
    environment:
      - SERVER_PUBLIC_ADDRESS=192.168.1.2
      - GAME_NAME="Vanilla Reforger Server"
      - RCON_PASSWORD="11223344"
      - GAME_PROPS_DISABLE_THIRD_PERSON=true
      - GAME_SCENARIO_ID="{C41618FD18E9D714}Missions/23_Campaign_Arland.conf" 
```
I found `{C41618FD18E9D714}Missions/23_Campaign_Arland.con` here `https://community.bistudio.com/wiki/Arma_Reforger:Server_Config#scenarioId`

**Comment by hafometh88** [comment]
```
---
version: '3.8'
services:
  arma-reforger:
    image: ghcr.dockerproxy.com/acemod/arma-reforger:latest
    platform: linux/amd64
    container_name: arma-reforger
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "19999:19999/udp"  # RCON
    volumes:
      - ./reforger/configs:/reforger/Configs
      - ./reforger/profile:/home/profile
      - ./reforger/workshop:/reforger/workshop
    environment:
      - SERVER_PUBLIC_ADDRESS=192.168.1.2
      - GAME_NAME=Vanilla Reforger Server
      - RCON_PASSWORD=11223344
      - GAME_PROPS_DISABLE_THIRD_PERSON=true
      - GAME_SCENARIO_ID={C41618FD18E9D714}Missions/23_Campaign_Arland.conf
```

Use it like above, the problem you have is the quotes around defined environment variables. If you add them, the final server config file is not valid because inside, they key-value pairs look like this: `scenarioId: ""{C41618FD18E9D714}Missions/23_Campaign_Arland.conf""`
