### ISSUE TITLE
Cache/Reload server files instead of redownloading every time

### ISSUE THREAD

**Issue by kiwidoggie** [acemod/docker-reforger#47]
More or less the title. Currently if you download the server, then set `SKIP_INSTALL=false` it won't be able to launch the server. Meaning that you have to re-download the Arma Reforger Server from steam every single time. This is a huge waste.

**Comment by hafometh88** [comment]
I agree, `SKIP_INSTALL=false` is currently broken and the server files do not persist. This can be "fixed" by mounting the game files volume to persist the files. Then it "only" verifies them on launch and does not have to redownload every time.

```
---
services:
  arma-reforger:
    image: ghcr.io/acemod/arma-reforger:latest
    platform: linux/amd64
    container_name: arma-reforger
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "19999:19999/udp"  # RCON
    volumes:
      - ./reforger/game:/reforger     <--- ADD THIS
      - ./reforger/configs:/reforger/Configs
      - ./reforger/profile:/home/profile
      - ./reforger/workshop:/reforger/workshop
    environment:
      - SERVER_PUBLIC_ADDRESS=public-ip
      - GAME_NAME=My Docker Reforger Server
```
